
name: Ansible Dev
on:
  push:
    branches: [ development ]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - name: Run ansible-lint
      - name: check dri
        run: pwd && ls
        # uses: ansible-community/ansible-lint-action@v6.0.2
        # with:
          
          # args: "ansible" # my ansible files in a folder

      - name: add cert
        shell: bash
        run: |
          mkdir -p keys
          touch ./keys/dev_private_key.pem
          echo -e "${{secrets.PRKEY}}" > ./keys/dev_private_key.pem

      - name: Execute Ansible Playbook
        uses: saubermacherag/ansible-playbook-docker-action@v1.4
        with:
          playbookName: 'main.yml'
          inventoryFile: 'inventory.ini'
  run-playbook:
    needs: [ validate ]
    runs-on: ubuntu-latest
    steps:
      - name: check dri
        run: pwd && ls
