run-playbook:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
		    # The validate Job need to be sucessfull
		needs: [ validate ]
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3
      - name: testing
        # uses: actions/setup-python@v2
        run: pwd && ls